Audio Controller
alex1600/kiwi-dev pull request #32
Opened 2021-09-16 00:44 UTC by PsykoDev

2021-09-16 01:02 UTC, Rehatla commented on UNITY/AudioController/Lib/DL.cs
> +            Process.Start("explorer.exe", "/select," + Directory.GetCurrentDirectory()+ "\\Assets");
ca va tout peter sur les macs :P

2021-09-16 07:35 UTC, alex1600 commented on UNITY/AudioController/Lib/DL.cs
> +            Process.Start("explorer.exe", "/select," + Directory.GetCurrentDirectory()+ "\\Assets");
A précisé dans le readme

2021-09-16 08:07 UTC, PsykoDev commented on UNITY/AudioController/Lib/DL.cs
> +            Process.Start("explorer.exe", "/select," + Directory.GetCurrentDirectory()+ "\\Assets");
j'ai mis dans le readme mais j'vais update le .cs après

2021-09-16 14:21 UTC, alex1600 requested changes

2021-09-19 16:27 UTC, alex1600 approved these changes

2021-09-19 16:27 UTC, merged