Update FPS
alex1600/kiwi-dev pull request #33
Opened 2021-09-16 11:46 UTC by PsykoDev

2021-09-16 11:50 UTC, NoonSense approved these changes

2021-09-16 14:20 UTC, alex1600 requested changes
intéressant la fenetre draggable mais qq modifs à faire encore

2021-09-16 14:20 UTC, alex1600 commented on UNITY/FPSDisplay/Script/FPSDisplay.cs
> +    public Rect startRect = new Rect(10, 10, 145, 40);
[SerializeField] private au lieu de public

2021-09-16 14:20 UTC, alex1600 commented on UNITY/FPSDisplay/Script/FPSDisplay.cs
> -    void Start()
Aere ton code avec une ligne

2021-09-16 14:20 UTC, alex1600 commented on UNITY/FPSDisplay/Script/FPSDisplay.cs
> +    IEnumerator FPS() {
Aere ton code avec une ligne

2021-09-16 14:20 UTC, alex1600 commented on UNITY/FPSDisplay/Script/FPSDisplay.cs
> +    void OnGUI() {
Aere ton code avec une ligne

2021-09-16 14:20 UTC, alex1600 commented on UNITY/FPSDisplay/Script/FPSDisplay.cs
> +    void FPSWindow(int windowID) {
Aere ton code avec une ligne

2021-09-16 14:20 UTC, alex1600 commented on UNITY/FPSDisplay/Script/FPSDisplay.cs
> +    private Rect ClampToScreen(Rect r) {
Aere ton code avec une ligne

2021-09-16 14:20 UTC, alex1600 commented on UNITY/FPSDisplay/Script/FPSDisplay.cs
> +        Invoke(nameof(GetMinMax), 1f);
Invoke dans un Update je suis contre, tu peux le remplacer avec un compteur que t'incremente avec time.deltaTime;
(quoi que je suis pas sur d'avoir compris ce que tu voulais réellement faire ici)

2021-09-16 14:20 UTC, alex1600 commented on UNITY/FPSDisplay/Script/FPSDisplay.cs
> +        if(MaxFPS < float.Parse(sFPS))
sFPS à remplacer en float pour éviter le parsing en boucle

2021-09-16 14:20 UTC, alex1600 commented on UNITY/FPSDisplay/Script/FPSDisplay.cs
> +            sFPS = fps.ToString("f" + Mathf.Clamp(nbDecimal, 0, 10));
c'est fps que tu devrais stocker en global

2021-09-16 14:20 UTC, alex1600 commented on UNITY/FPSDisplay/Script/FPSDisplay.cs
> +        GUI.Label(new Rect(0, 0, startRect.width, startRect.height), $"{sFPS} FPS\n[{MinFPS}Min {MaxFPS}Max]", style);
sFPS à remplacer par FPS ça tombe bien car tu fais de l'interpolation de string donc tu va pouvoir faire ça : 
$"{Math.Round(fps, nbDecimal ) ect... 
(à confirmer)

2021-09-16 14:33 UTC, NoonSense commented on UNITY/FPSDisplay/Script/FPSDisplay.cs
> +        Invoke(nameof(GetMinMax), 1f);
Même InvokeRepeating() dans le start est mieux

2021-09-17 11:04 UTC, alex1600 approved these changes

2021-09-17 11:05 UTC, merged